#!/bin/bash

ragel src/g-scope-parser.rl -o scr/g-scope-parser.c
ragel src/g-rule-parser.rl -o src/g-rule-parser.c

sudo cp example.ruleset.gt /etc/nginx/gauntlet-ruleset.gt
cd ../nginx-1.0.11
make -j2
sudo make install

